### ISSUE TITLE
Problem with webhook when you place order (error 500)

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-snipcartshop-plugin#11]
Hello,

I continue my tests with snipcart and tried to place a test order on the website.

I could correctly go throught the checkout process, but, once order is placed, I get a email from the snipcart team saying me that the webhook didn't work correctly.

If I go to the webhook log on snipcart website and see the details, I can see that the URL called return an error :

> SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: offline_snipcartshop_orders.invoice_number

Any ideas about the problem ?

**Comment by tobias-kuendig** [comment]
This is because of the way SQLite handles nullable fields. Try to update the plugin to the latest version 1.0.24 to get better SQLite support. 

Please report back if you experience any further issues.

**Comment by Zmove** [comment]
I updated the plugin and placed a new order. It seems better as I can see the order detail in the october backend.

However, I don't see the product line item. I have the addresses, subtotals, but no products (see [attached screenshot](http://imageshack.com/a/img923/2905/18FT4J.png)).

**Comment by tobias-kuendig** [comment]
Do you see any errors in your `system.log`? It's possible that it cannot save entries into your orders_products table since there are some null values present.

**Comment by Zmove** [comment]
Hello,

Yes, if I go to the logs, I see the following error :

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: offline_snipcartshop_order_items.max_quantity in www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:390

**Comment by tobias-kuendig** [comment]
Thanks I'll take a look at it.

**Comment by tobias-kuendig** [comment]
This is fixed in version 1.0.26. Thank you for your report.
