### ISSUE TITLE
List all products in a partial

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-snipcartshop-plugin#14]
Hello,

I'm trying to customize the markup of my product list. To do that, I use the october CMS way, I call a partial /shop/list.htm and I add the component in my partial and try to loop throught the {{ products }} variable.

But it doesn't work. If I print {{ products }} I don't get the products object, it just display a "products" string.

It works if I put the component in a page.

Is there any limitation that could explain that I can work in a partial ? Cause I did this for the blog for example, and it perfectly works...

Thanks for your help

Alex

**Comment by tobias-kuendig** [comment]
Try `{{ products.products }}`. You have to call the `products` property on the `products` component.

**Comment by Zmove** [comment]
Thank you, it worked.
