### ISSUE TITLE
Error when adding dropdown custom field

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-snipcartshop-plugin#17]
Hello,

When I add a custom field dropdown with some options, I get an error when I click the "create" button

> "SQLSTATE[HY000]: General error: 20 datatype mismatch (SQL: insert into "offline_snipcartshop_product_custom_field_options" ("id", "name", "price", "sort_order", "updated_at", "created_at") values (, Option 1, 500, 0, 2017-06-14 13:54:22, 2017-06-14 13:54:22))" on line 666 of www/vendor/laravel/framework/src/Illuminate/Database/Connection.php

Regards,

Alex

**Comment by tobias-kuendig** [comment]
Fixed in 1.0.27. Thanks!
