### ISSUE TITLE
How to customize the formatted price ?

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-snipcartshop-plugin#20]
Hello,

I noticed that, when you want to display the formatted price, there is a {{ product.priceFormatted }} twig variable.

However, it display price like that (example with euros) :

    EUR 10.00

How to display price like that :

    10,00€

In addition,  it would be great to display if the price is including or excluding taxes, for example :

    10,00€ (Inc. VAT) or 10,00€ (Exc. VAT)

Thank you for your help

Alex

**Comment by tobias-kuendig** [comment]
This is currently not possible. At the moment you can simply use the `price` property and format it yourself (maybe with a custom twig filter).

I haven't come across a simple solution for this problem yet. The format will have to be specified on a per currency basis. Maybe I'll add a format field to the currency repeater where this format can be customized.

**Comment by Alex360hd** [comment]
Yes, I think the best way to do that is to let user defined it's own code to format the price for each currency with some token available.

I think about [something like that](https://ibb.co/csKNOQ)

**Comment by tobias-kuendig** [comment]
I have implemented this feature based on your ideas in version `1.0.33`. It's available via edge updates. Feel free to test it!

**Comment by Alex360hd** [comment]
You are the best ! I will test that

**Comment by tobias-kuendig** [comment]
Closed due to inactivity.
