### ISSUE TITLE
Snipcart Subscriptions

### ISSUE THREAD

**Issue by jeubanks** [OFFLINE-GmbH/oc-snipcartshop-plugin#27]
Does this plugin support Snipcart subscriptions?

**Comment by tobias-kuendig** [comment]
No, currently only products are supported and there are no plans to extend it to support subscriptions. If you want to submit a PR feel free to do so!

**Comment by jeubanks** [comment]
I'm not a php developer but I'll play around with it.  I see in the plugin
classes there's DataAttributes.php and it looks like there's a way to
add/substitute the Snipcart data- fields?  For someone that knows this
plugin and php adding a recurring option is changing 3 lines of the data
paremeter passed to snipcart.... oh well time to mess around with it and
see how badly I can break it.
