### ISSUE TITLE
Exception when clicking to shop link in the backoffice on a fresh install

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-snipcartshop-plugin#4]
Hello,

Just after an install, if you click on the shop link, you got an exception :

> Class 'RainLab\Translate\Behaviors\TranslatableModel' not found

In the file
 
> /vendor/october/rain/src/Extension/ExtendableTrait.php line 196

I think that's because the plugin depend on the rainlab translate plugin, but it's not mentionned anywhere (just said that it have multilanguage possibilities)

**Comment by tobias-kuendig** [comment]
Fixed in 1.0.5. Thanks for bringing this issue to our attention! :+1:
