### ISSUE TITLE
Show a continue shopping button

### ISSUE THREAD

**Issue by tekjava** [OFFLINE-GmbH/oc-snipcartshop-plugin#6]
Here is how you can add the Continue Shopping button to the cart.

Will need to expand the dependencies component code and add this:
`Snipcart.execute('config', 'show_continue_shopping', true);`

The second script in the dependencies component code should look like this:
`<script>`
   ` Snipcart.api.cart.currency('{{ snipcartDependencies.activeCurrency | lower }}');`
    `Snipcart.execute('config', 'show_continue_shopping', true);`
`</script>`

This would be a nice addition as an option in configuration settings. :)

**Comment by tobias-kuendig** [comment]
This will be available in version 1.0.21. Thank you for your input!
