### ISSUE TITLE
"Object of class October\Rain\Database\Builder could not be converted to int" on line 177

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-snipcartshop-plugin#9]
Hello,

I installed snipcart, configured the global settings, created some sample product and now I'm trying to display simple product listing on a page.

When I add the "Products" component to my page and I click on it to configure it, I get the following popup error :

> "Object of class October\Rain\Database\Builder could not be converted to int" on line 177 of /www/plugins/offline/snipcartshop/components/Products.php

I have many plugins and only this one give me that error.

I'm using SQLite database engine.

**Comment by tobias-kuendig** [comment]
Did you create any categories?

**Comment by Alex360hd** [comment]
Hello,

No I didn't create any categories yet. I will check that.

**Comment by tobias-kuendig** [comment]
That would be great. If it works after creating a category I can release a fix for this bug with the next version.

**Comment by Alex360hd** [comment]
I confirm that creating a category resolve the problem.

Thanks for your support !

**Comment by tobias-kuendig** [comment]
Great, I will release a fix with the next version. Thanks for reporting this bug! :+1:

**Comment by tobias-kuendig** [comment]
This fix will be available in version 1.0.22 that will be released later today.
